import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createBackend} from '../src/backend.mjs';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';

async function setup(){const {server,db}=createBackend({dbPath:':memory:',adminToken:'test-secret'});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;return {base,close:()=>{server.close();db.close()}};}
const request=(base,path,method='GET',data,token)=>fetch(base+path,{method,headers:{'Content-Type':'application/json',...(token?{'x-admin-token':token}:{})},body:data?JSON.stringify(data):undefined});

test('seeded content, editorial content and admin protection',async()=>{const s=await setup();try{const listings=await (await request(s.base,'/api/listings')).json();assert.ok(listings.some(x=>x.section==='estate'&&x.photos.length>1));assert.ok(listings.some(x=>x.section==='estate'&&x.location.includes('Visakhapatnam')));assert.ok(listings.some(x=>x.section==='boutique'));assert.ok(listings.some(x=>x.section==='car'));const stories=await (await request(s.base,'/api/editorials')).json();assert.equal(stories.length,5);assert.ok(stories.every(x=>x.titleTe&&x.bodyTe));assert.ok(stories.some(x=>x.id==='ai-property-search'));assert.equal((await request(s.base,'/api/admin/enquiries')).status,401);}finally{s.close()}});

test('all publish pages and car assets are served',async()=>{const s=await setup();try{for(const path of ['/','/estate.html','/properties.html','/property.html','/boutique.html','/collection.html','/cars.html','/admin.html','/src/public.mjs','/src/car-view.mjs','/src/car.css','/src/estate-extras.mjs']){const response=await fetch(s.base+path);assert.equal(response.status,200,path);assert.ok((await response.text()).length>100,path)}const car=await (await fetch(s.base+'/cars.html')).text();assert.match(car,/data-page="car"/);assert.match(car,/car\.css/);assert.equal((await fetch(s.base+'/api/health')).status,200)}finally{s.close()}});

test('published estate metadata and sitemap use current database content',async()=>{const {server,db}=createBackend({dbPath:':memory:',siteUrl:'https://estate.example',publishReady:true});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;try{const page=await (await fetch(base+'/property.html?id=e5')).text();assert.match(page,/Araku Road Plot/);assert.match(page,/rel="canonical" href="https:\/\/estate\.example\/property\.html\?id=e5"/);const article=await (await fetch(base+'/article.html?id=ai-property-search')).text();assert.match(article,/application\/ld\+json/);const sitemap=await (await fetch(base+'/sitemap.xml')).text();assert.match(sitemap,/ai-property-search/);assert.match(sitemap,/property\.html\?id=e5/);assert.match(sitemap,/properties\.html/);const robots=await (await fetch(base+'/robots.txt')).text();assert.match(robots,/Sitemap: https:\/\/estate\.example\/sitemap\.xml/);assert.match(robots,/Disallow: \/admin\.html/);}finally{await new Promise(resolve=>server.close(resolve));db.close()}});

test('car edits keep multilingual media and are immediately public',async()=>{const s=await setup();try{const item={section:'car',kind:'Rental',kindTe:'అద్దె కారు',intent:'Rent',title:'Test motor',titleTe:'పరీక్ష కారు',detail:'2024 · automatic',detailTe:'2024 · ఆటోమేటిక్',price:'Price on request',photos:['https://example.com/front.jpg','https://example.com/back.jpg'],videos:['https://example.com/walkthrough.mp4']};const created=await (await request(s.base,'/api/listings','POST',item,'test-secret')).json();assert.equal(created.titleTe,item.titleTe);assert.deepEqual(created.videos,item.videos);const updated=await (await request(s.base,'/api/listings','PUT',{...created,title:'Updated motor',titleTe:'మార్చిన కారు'},'test-secret')).json();assert.equal(updated.title,'Updated motor');const cars=await (await request(s.base,'/api/listings?section=car')).json();const publicItem=cars.find(x=>x.id===created.id);assert.equal(publicItem.titleTe,'మార్చిన కారు');assert.equal(publicItem.photos.length,2);assert.equal(publicItem.videos.length,1);assert.equal(publicItem.intent,'Rent')}finally{s.close()}});

test('listing changes appear through public API',async()=>{const s=await setup();try{const item={section:'boutique',kind:'Dresses',title:'Test dress',price:'₹100',photos:['https://example.com/one.jpg','https://example.com/two.jpg'],sizes:['S','M']};const unauthorized=await request(s.base,'/api/listings','POST',item);assert.equal(unauthorized.status,401);const created=await (await request(s.base,'/api/listings','POST',item,'test-secret')).json();assert.ok(created.id);assert.equal(created.photos.length,2);const publicItems=await (await request(s.base,'/api/listings?section=boutique')).json();assert.ok(publicItems.some(x=>x.id===created.id));const invalid=await request(s.base,'/api/listings','PUT',{...created,photos:['javascript:alert(1)']},'test-secret');assert.equal(invalid.status,400);assert.equal((await request(s.base,`/api/listings/${created.id}`,'DELETE',undefined,'test-secret')).status,200);const after=await (await request(s.base,'/api/listings?section=boutique')).json();assert.ok(!after.some(x=>x.id===created.id));}finally{s.close()}});

test('business links are editable and unsafe social URLs are removed',async()=>{const s=await setup();try{assert.equal((await request(s.base,'/api/settings','PUT',{phone:'9876543210'})).status,401);const saved=await (await request(s.base,'/api/settings','PUT',{phone:'9876543210',address:'Visakhapatnam',instagram:'https://instagram.com/example',facebook:'javascript:alert(1)'},'test-secret')).json();assert.equal(saved.phone,'9876543210');assert.equal(saved.facebook,'');const publicSettings=await (await request(s.base,'/api/settings')).json();assert.equal(publicSettings.instagram,'https://instagram.com/example');assert.equal(publicSettings.address,'Visakhapatnam')}finally{s.close()}});

test('edited property and clothing specifications are published immediately',async()=>{const s=await setup();try{const property={section:'estate',kind:'Commercial plot',title:'Custom plot',price:'Price on request',location:'Sheela Nagar',mapQuery:'Sheela Nagar, Visakhapatnam',amenities:'Road access, Open space',photos:['https://example.com/plot.jpg']};const clothing={section:'boutique',kind:'Dresses',title:'Custom dress',price:'₹1,000',material:'Cotton',fit:'Regular',care:'Cold wash',sizes:['S','M'],photos:['https://example.com/dress.jpg']};const a=await (await request(s.base,'/api/listings','POST',property,'test-secret')).json(),b=await (await request(s.base,'/api/listings','POST',clothing,'test-secret')).json();const publicItems=await (await request(s.base,'/api/listings')).json();assert.equal(publicItems.find(x=>x.id===a.id).mapQuery,'Sheela Nagar, Visakhapatnam');assert.equal(publicItems.find(x=>x.id===a.id).amenities,'Road access, Open space');assert.equal(publicItems.find(x=>x.id===b.id).material,'Cotton');assert.equal(publicItems.find(x=>x.id===b.id).care,'Cold wash')}finally{s.close()}});

test('estate, boutique and car calls reach one Sheet queue with their source',async()=>{const seen=[];const {server,db,delivery}=createBackend({dbPath:':memory:',adminToken:'test-secret',sheetUrl:'https://example.com/hook',sheetSecret:'secret',fetcher:async(_url,options)=>{const item=JSON.parse(options.body).request;seen.push(item.source);return {ok:true,json:async()=>({ok:true,id:item.id})}}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;try{for(const source of ['estate','boutique','car'])assert.equal((await request(base,'/api/enquiries','POST',{name:'Asha',phone:'9876543210',consent:true,source})).status,201);await delivery.syncPending();assert.deepEqual([...new Set(seen)].sort(),['boutique','car','estate']);assert.equal(delivery.status().pending,0)}finally{await new Promise(resolve=>server.close(resolve));db.close()}});

test('studio listing edits notify an open public page',async()=>{const s=await setup();let reader;try{const stream=await fetch(s.base+'/api/events');assert.equal(stream.status,200);reader=stream.body.getReader();await reader.read();const item={section:'car',kind:'Pre-owned',title:'Edited car',price:'Price on request',photos:['https://example.com/car.jpg']};assert.equal((await request(s.base,'/api/listings','POST',item,'test-secret')).status,200);const next=await Promise.race([reader.read(),new Promise((_,reject)=>setTimeout(()=>reject(Error('No update event')),2000))]);assert.match(new TextDecoder().decode(next.value),/"section":"car"/)}finally{if(reader)await reader.cancel();await new Promise(resolve=>s.close()||resolve())}});

test('enquiry validation and persisted call request',async()=>{const s=await setup();try{assert.equal((await request(s.base,'/api/enquiries','POST',{name:'A',phone:'123',consent:true})).status,400);const sent=await request(s.base,'/api/enquiries','POST',{name:'Asha',phone:'9876543210',consent:true,item:'Coastal Courtyard Villa',source:'estate',goal:'Buy',area:'Madhurawada',budget:'₹2–3 Cr',note:'Please call'});assert.equal(sent.status,201);const rows=await (await request(s.base,'/api/admin/enquiries','GET',undefined,'test-secret')).json();assert.equal(rows.length,1);assert.equal(rows[0].item,'Coastal Courtyard Villa');assert.equal(rows[0].goal,'Buy');assert.equal(rows[0].area,'Madhurawada');assert.match(rows[0].note,/Budget: ₹2–3 Cr/);}finally{s.close()}});

test('phone-only car enquiry is saved for a callback',async()=>{const s=await setup();try{assert.equal((await request(s.base,'/api/enquiries','POST',{phone:'9876543210',consent:true,source:'car'})).status,201);const rows=await (await request(s.base,'/api/admin/enquiries','GET',undefined,'test-secret')).json();assert.equal(rows[0].name,'Website visitor');assert.equal(rows[0].source,'car')}finally{s.close()}});

test('boutique reviews require a verified purchase code and approval',async()=>{const s=await setup();try{const payload={listingId:'b1',name:'Asha',rating:5,comment:'Lovely fit'};assert.equal((await request(s.base,'/api/reviews','POST',payload)).status,400);const enquiry=await (await request(s.base,'/api/enquiries','POST',{name:'Asha',phone:'9876543210',consent:true,source:'boutique',item:'The City Coat',itemId:'b1'})).json();assert.equal((await request(s.base,`/api/admin/enquiries/${enquiry.id}/review-invite`,'POST',{})).status,401);const invite=await (await request(s.base,`/api/admin/enquiries/${enquiry.id}/review-invite`,'POST',{},'test-secret')).json();assert.ok(invite.reviewCode);const pending=await (await request(s.base,'/api/reviews','POST',{...payload,reviewCode:invite.reviewCode})).json();assert.equal(pending.status,'pending');assert.equal((await request(s.base,'/api/reviews','POST',{...payload,reviewCode:invite.reviewCode})).status,403);assert.equal((await (await request(s.base,'/api/reviews?listing=b1')).json()).length,0);const approved=await request(s.base,`/api/admin/reviews/${pending.id}`,'PATCH',{status:'approved'},'test-secret');assert.equal(approved.status,200);const rows=await (await request(s.base,'/api/reviews?listing=b1')).json();assert.equal(rows.length,1);assert.equal(rows[0].verifiedPurchase,true);assert.equal((await request(s.base,'/api/reviews','POST',{listingId:'e1',name:'Asha',rating:5,comment:'No'})).status,400);}finally{s.close()}});

test('editorials can be edited and the database is not served as a file',async()=>{const s=await setup();try{const created=await (await request(s.base,'/api/editorials','POST',{title:'New article',titleTe:'కొత్త వ్యాసం',body:'Useful details',bodyTe:'ఉపయోగకరమైన వివరాలు'},'test-secret')).json();assert.ok(created.id);assert.ok((await (await request(s.base,'/api/editorials')).json()).some(x=>x.id===created.id));assert.equal((await request(s.base,'/data/site.sqlite')).status,403);}finally{s.close()}});

test('SQLite content survives a backend restart',async()=>{const dir=await mkdtemp(join(tmpdir(),'ravi-site-'));const path=join(dir,'site.sqlite');try{const first=createBackend({dbPath:path});first.db.prepare('INSERT INTO enquiries VALUES(?,?,?)').run('saved-id',JSON.stringify({id:'saved-id',name:'Saved visitor'}),new Date().toISOString());first.db.close();const second=createBackend({dbPath:path});try{assert.equal(second.db.prepare('SELECT COUNT(*) n FROM enquiries').get().n,1);assert.equal(second.db.prepare('SELECT COUNT(*) n FROM listings').get().n,16)}finally{second.db.close()}}finally{assert.ok(resolve(dir).startsWith(resolve(tmpdir())+sep));await rm(dir,{recursive:true,force:true,maxRetries:10,retryDelay:100})}});

test('deleted sample listings stay deleted after restart',async()=>{const dir=await mkdtemp(join(tmpdir(),'ravi-delete-'));const path=join(dir,'site.sqlite');try{const first=createBackend({dbPath:path});first.db.prepare('DELETE FROM listings').run();first.db.prepare('DELETE FROM editorials').run();first.db.close();const second=createBackend({dbPath:path});try{assert.equal(second.db.prepare('SELECT COUNT(*) n FROM listings').get().n,0);assert.equal(second.db.prepare('SELECT COUNT(*) n FROM editorials').get().n,0)}finally{second.db.close()}}finally{assert.ok(resolve(dir).startsWith(resolve(tmpdir())+sep));await rm(dir,{recursive:true,force:true,maxRetries:10,retryDelay:100})}});

test('video upload validates format and supports playback ranges',async()=>{const dir=await mkdtemp(join(tmpdir(),'ravi-video-'));const {server,db}=createBackend({dbPath:':memory:',staticRoot:dir,adminToken:'test-secret'});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;try{const invalid=await fetch(base+'/api/media',{method:'POST',headers:{'Content-Type':'video/mp4','x-admin-token':'test-secret'},body:Buffer.from('not a video')});assert.equal(invalid.status,400);const bytes=Buffer.concat([Buffer.from([0,0,0,24]),Buffer.from('ftypisom'),Buffer.alloc(16)]);const uploaded=await fetch(base+'/api/media',{method:'POST',headers:{'Content-Type':'video/mp4','x-admin-token':'test-secret'},body:bytes});assert.equal(uploaded.status,201);const {url}=await uploaded.json();assert.match(url,/^\/uploads\/[a-f0-9-]+\.mp4$/);const media=await fetch(base+url);assert.equal(media.headers.get('content-type'),'video/mp4');assert.deepEqual(Buffer.from(await media.arrayBuffer()),bytes);const part=await fetch(base+url,{headers:{Range:'bytes=4-7'}});assert.equal(part.status,206);assert.equal(part.headers.get('content-range'),`bytes 4-7/${bytes.length}`);assert.deepEqual(Buffer.from(await part.arrayBuffer()),bytes.subarray(4,8));}finally{await new Promise(resolve=>server.close(resolve));db.close();assert.ok(resolve(dir).startsWith(resolve(tmpdir())+sep));await rm(dir,{recursive:true,force:true,maxRetries:10,retryDelay:100})}});

test('call requests sync to the configured Sheet and retry after failure',async()=>{let fail=true,calls=0;const fetcher=async(_url,options)=>{calls++;const payload=JSON.parse(options.body);assert.equal(payload.secret,'test-secret');if(fail)throw Error('temporary outage');return {ok:true,json:async()=>({ok:true,id:payload.request.id})}};const {server,db,delivery}=createBackend({dbPath:':memory:',adminToken:'admin-secret',sheetUrl:'https://example.com/webhook',sheetSecret:'test-secret',fetcher});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;try{const created=await (await request(base,'/api/enquiries','POST',{name:'Asha',phone:'9876543210',consent:true,source:'car'})).json();for(let i=0;i<30;i++){const status=db.prepare('SELECT data FROM enquiries WHERE id=?').get(created.id);if(JSON.parse(status.data).sheetStatus==='failed')break;await new Promise(r=>setTimeout(r,10))}assert.equal(JSON.parse(db.prepare('SELECT data FROM enquiries WHERE id=?').get(created.id).data).sheetStatus,'failed');fail=false;const synced=await request(base,'/api/admin/sheets/sync','POST',{},'admin-secret');assert.equal(synced.status,200);const saved=JSON.parse(db.prepare('SELECT data FROM enquiries WHERE id=?').get(created.id).data);assert.equal(saved.sheetStatus,'synced');assert.equal(saved.source,'car');assert.equal(calls,2);assert.equal((await delivery.syncOne(created.id)).alreadySynced,true)}finally{await new Promise(resolve=>server.close(resolve));db.close()}});

test('requests saved before Sheet setup are included in later sync',async()=>{const received=[];const {db,delivery}=createBackend({dbPath:':memory:',sheetUrl:'https://example.com/webhook',sheetSecret:'secret',fetcher:async(_url,options)=>{const item=JSON.parse(options.body).request;received.push(item.id);return {ok:true,json:async()=>({ok:true,id:item.id})}}});try{db.prepare('INSERT INTO enquiries VALUES(?,?,?)').run('earlier-request',JSON.stringify({id:'earlier-request',name:'Asha',phone:'9876543210',sheetStatus:'not_configured'}),new Date().toISOString());assert.equal(delivery.status().pending,1);await delivery.syncPending();assert.deepEqual(received,['earlier-request']);assert.equal(delivery.status().pending,0)}finally{db.close()}});
