import {estate,boutique,cars,photos} from './data.mjs';
import {BUSINESS_WHATSAPP,escapeHTML,filterListings,readDemoListings,readDemoEnquiries,saveDemoEnquiries,validateEnquiry,whatsappURL} from './core.mjs';

const page=document.body.dataset.page;
const app=document.querySelector('#app');
const state={style:localStorage.getItem('rs-style')||'editorial',intent:'All',kind:'All',search:'',category:'Clothing',selected:null,selectedSize:''};
const sampleNote='Concept content and sample imagery. Actual listings, availability and prices will be added before launch.';
const getItems=section=>[...(section==='estate'?estate:section==='boutique'?boutique:cars),...readDemoListings().filter(x=>x.section===section)];
const icon=(name)=>({arrow:'↗',plus:'+',close:'×',heart:'♡',pin:'⌖'}[name]||'');
const img=(url,alt,extra='')=>url?`<img src="${escapeHTML(url)}" alt="${escapeHTML(alt)}" ${extra} onerror="this.classList.add('image-fallback')">`:'<span class="photo-placeholder">PHOTO COMING SOON</span>';

function chrome(active){return `<div class="announcement"><span>Two connected website concepts · design preview</span><a href="/admin.html">Open mobile listing studio ${icon('arrow')}</a></div>
<header class="site-header"><a class="wordmark" href="/"><span class="mark">RS</span><span>RAVI SETH <small>CONCEPTS</small></span></a>
<nav aria-label="Main navigation"><a class="${active==='estate'?'active':''}" href="/estate.html">Real estate</a><a class="${active==='boutique'?'active':''}" href="/boutique.html">Boutique & cars</a><a href="/admin.html">Listing studio</a></nav>
<div class="header-actions"><div class="style-switch" role="group" aria-label="Visual style"><button data-style="editorial" aria-pressed="${state.style==='editorial'}">01 Editorial</button><button data-style="modern" aria-pressed="${state.style==='modern'}">02 Modern</button></div><button class="mobile-menu" aria-label="Open menu" aria-expanded="false">☰</button></div></header>`;}

function footer(){return `<footer class="site-footer"><div><a class="wordmark" href="/"><span class="mark">RS</span><span>RAVI SETH <small>CONCEPTS</small></span></a><p>Properties, clothing and cars.</p></div><div><strong>Explore</strong><a href="/estate.html">Real estate</a><a href="/boutique.html">Boutique & cars</a><a href="/admin.html">Listing studio</a></div><div><strong>Get in touch</strong><p>Phone and WhatsApp details will be added before launch.</p><button class="text-button" data-open-enquiry>Request a call ↗</button></div><div class="footer-bottom"><span>© 2026 Ravi Seth · Design concept</span><span>${sampleNote}</span></div></footer>`;}

function home(){return `${chrome('home')}<main><section class="home-intro"><p class="eyebrow">TWO WORLDS, ONE STANDARD</p><h1>Two collections.<br><em>One place to begin.</em></h1><p>Explore the property and boutique previews. Use the style control above to compare two visual directions.</p></section><section class="portal-grid"><a class="portal" href="/estate.html">${img(photos.estateHero,'Modern home interior')}<span class="portal-shade"></span><span class="portal-copy"><span class="eyebrow">01 / PROPERTY</span><strong>Real estate</strong><span>Homes and spaces for sale or rent <b>↗</b></span></span></a><a class="portal" href="/boutique.html">${img(photos.boutiqueHero,'Fashion editorial portrait')}<span class="portal-shade"></span><span class="portal-copy"><span class="eyebrow">02 / COLLECTIONS</span><strong>Boutique & cars</strong><span>Clothing first, with a curated motor section <b>↗</b></span></span></a></section><div class="home-note"><span>DESIGN 01</span><p>Editorial: warm, tactile and refined</p><span>DESIGN 02</span><p>Modern: bold, crisp and high contrast</p></div></main>${footer()}${modalShell()}`;}

function estateCard(x){return `<article class="listing-card"><button class="card-image" data-detail="${escapeHTML(x.id)}" aria-label="View ${escapeHTML(x.title)}">${img(x.image,x.title,'loading="lazy"')}<span class="card-tag">${escapeHTML(x.intent||'Sale')}</span></button><div class="card-copy"><div class="card-meta"><span>${escapeHTML(x.kind)}</span><span>${escapeHTML(x.detail||'')}</span></div><h3>${escapeHTML(x.title)}</h3><p class="location">${icon('pin')} ${escapeHTML(x.location||'Location to be added')}</p><div class="card-bottom"><strong>${escapeHTML(x.price)}</strong><button data-detail="${escapeHTML(x.id)}" aria-label="View ${escapeHTML(x.title)}">↗</button></div></div></article>`;}
function boutiqueCard(x){return `<article class="listing-card product-card"><button class="card-image" data-detail="${escapeHTML(x.id)}" aria-label="View ${escapeHTML(x.title)}">${img(x.image,x.title,'loading="lazy"')}<span class="card-tag">${escapeHTML(x.kind)}</span></button><div class="card-copy"><div class="card-meta"><span>${x.sizes?.length?'Available sizes':'Listing details'}</span><span>${x.sizes?.length?escapeHTML(x.sizes.join(' · ')):escapeHTML(x.detail||'Ask for details')}</span></div><h3>${escapeHTML(x.title)}</h3><div class="card-bottom"><strong>${escapeHTML(x.price)}</strong><button data-detail="${escapeHTML(x.id)}" aria-label="View ${escapeHTML(x.title)}">↗</button></div></div></article>`;}

function estatePage(){return `${chrome('estate')}<main><section class="hero estate-hero"><div class="hero-art">${img(photos.estateHero,'Warm modern home interior')}</div><div class="hero-content"><p class="eyebrow">REAL ESTATE / SALE & RENT</p><h1>Find your next<br><em>address.</em></h1><p>Browse homes, plots and commercial spaces for sale or rent. Request a call to ask questions or arrange a visit.</p><div class="hero-actions"><a class="button button-light" href="#listings">Explore properties <span>↗</span></a><button class="button button-outline-light" data-open-enquiry>Request a call</button></div><div class="hero-shortcuts"><span>QUICK BROWSE</span><button data-quick-intent="Sale">For sale ↗</button><button data-quick-intent="Rent">For rent ↗</button><button data-quick-kind="Apartment">Apartments ↗</button></div></div><div class="hero-foot"><span>01 / THE PROPERTY EDIT</span><span>SCROLL TO EXPLORE ↓</span></div></section>
<section class="section intro-band"><div><p class="eyebrow">THE COLLECTION</p><h2>See the details<br><em>before you call.</em></h2></div><p>Filter by sale or rent, property type and area. Open a listing for its price, size and location.</p></section>
<section id="listings" class="section listings-section"><div class="section-title"><div><p class="eyebrow">DISCOVER</p><h2>Featured properties</h2></div><span class="results" id="result-count"></span></div><div class="filters"><div class="segmented" role="group" aria-label="Sale or rent"><button class="active" data-intent="All">All</button><button data-intent="Sale">For sale</button><button data-intent="Rent">For rent</button></div><label class="search-box"><span>⌕</span><input id="estate-search" type="search" placeholder="Search by name, type or area" aria-label="Search properties"></label><select id="estate-kind" aria-label="Property type"><option>All</option><option>Villa</option><option>House</option><option>Apartment</option><option>Plot</option><option>Commercial</option></select></div><div id="estate-grid" class="listing-grid"></div><p id="empty-state" class="empty-state" hidden>No properties match these filters. Try another search.</p></section>
<section class="process-section section"><div><p class="eyebrow">VISITING A PROPERTY</p><h2>How a viewing<br><em>takes shape.</em></h2></div><div class="process-grid"><div><span>01</span><h3>Explore</h3><p>Browse property details and shortlist the spaces you like.</p></div><div><span>02</span><h3>Request a call</h3><p>Leave your number and the listing you want to discuss.</p></div><div><span>03</span><h3>Plan a visit</h3><p>We confirm availability and arrange a convenient time by phone.</p></div></div></section><section class="cta-section"><p class="eyebrow">LET'S BEGIN</p><h2>Ask about a listing<br>or <em>arrange a visit.</em></h2><button class="button button-dark" data-open-enquiry>Request a call <span>↗</span></button></section></main>${footer()}${modalShell()}`;}

function boutiquePage(){return `${chrome('boutique')}<main><section class="hero boutique-hero"><div class="hero-art">${img(photos.boutiqueHero,'Fashion editorial portrait')}</div><div class="hero-content"><p class="eyebrow">THE BOUTIQUE / A CURATED EDIT</p><h1>The clothing<br><em>edit.</em></h1><p>Browse dresses, outerwear and everyday pieces. Check sizes, then ask about fit or availability.</p><div class="hero-actions"><a class="button button-light" href="#collection">Shop the edit <span>↗</span></a><button class="button button-outline-light" data-open-enquiry>Request a call</button></div></div><div class="hero-foot"><span>01 / CLOTHING FIRST</span><span>SCROLL TO EXPLORE ↓</span></div></section>
<section class="section intro-band"><div><p class="eyebrow">DISCOVER THE EDIT</p><h2>Explore by<br><em>category and size.</em></h2></div><p>Find the details that matter before you call. Cars have their own section so clothing stays at the centre of the boutique.</p></section>
<section id="collection" class="section listings-section"><div class="section-title"><div><p class="eyebrow">THE COLLECTION</p><h2>Explore what’s new</h2></div><span class="results" id="result-count"></span></div><div class="filters"><div class="segmented" role="group" aria-label="Collection"><button class="active" data-category="Clothing">Clothing</button><button data-category="Cars">Cars</button></div><label class="search-box"><span>⌕</span><input id="collection-search" type="search" placeholder="Search the collection" aria-label="Search collection"></label><select id="collection-kind" aria-label="Category"><option>All</option></select></div><div id="collection-grid" class="listing-grid"></div><p id="empty-state" class="empty-state" hidden>No items match these filters. Try another search.</p></section>
<section class="process-section section"><div><p class="eyebrow">ASKING ABOUT AN ITEM</p><h2>From product page<br>to <em>phone call.</em></h2></div><div class="process-grid"><div><span>01</span><h3>Browse</h3><p>View images, details and available sizes.</p></div><div><span>02</span><h3>Enquire</h3><p>Request a call about an item you like.</p></div><div><span>03</span><h3>Confirm</h3><p>Availability, fit or a visit can be discussed personally.</p></div></section><section class="cta-section"><p class="eyebrow">PERSONAL SERVICE</p><h2>Questions about fit<br>or <em>availability?</em></h2><button class="button button-dark" data-open-enquiry>Request a call <span>↗</span></button></section></main>${footer()}${modalShell()}`;}

function modalShell(){return `<dialog id="detail-dialog" class="dialog detail-dialog"><button class="dialog-close" data-close aria-label="Close details">×</button><div id="detail-content"></div></dialog><dialog id="enquiry-dialog" class="dialog enquiry-dialog"><button class="dialog-close" data-close aria-label="Close enquiry">×</button><div class="enquiry-wrap"><p class="eyebrow">LET'S CONNECT</p><h2>Request a call</h2><p>Share your number and we’ll use it to discuss your enquiry or arrange a visit. This preview saves requests on this device only.</p><form id="enquiry-form" novalidate><input type="hidden" name="item"><label>Your name <input name="name" autocomplete="name" required placeholder="Full name"></label><label>Phone number <input name="phone" autocomplete="tel" inputmode="tel" required placeholder="Your mobile number"></label><label>What would you like to discuss? <textarea name="note" rows="3" placeholder="A listing, size, visit or question"></textarea></label><label class="check-label"><input name="consent" type="checkbox"> I agree to be contacted about this enquiry.</label><p class="form-error" id="form-error" role="alert"></p><button class="button button-dark" type="submit">Save request <span>↗</span></button></form><div id="enquiry-success" hidden></div><div class="whatsapp-row"><span>Prefer WhatsApp?</span><button id="whatsapp-button" class="text-button">Continue in WhatsApp ↗</button></div></div></dialog>`;}

function currentList(){return page==='estate'?getItems('estate'):state.category==='Clothing'?getItems('boutique'):getItems('car');}
function refreshCards(){
  const items=filterListings(currentList(),{intent:page==='estate'?state.intent:'All',kind:state.kind,search:state.search});
  const grid=document.querySelector(page==='estate'?'#estate-grid':'#collection-grid');
  grid.innerHTML=items.map(page==='estate'?estateCard:boutiqueCard).join('');
  document.querySelector('#result-count').textContent=`${items.length} ${page==='estate'?'properties':state.category==='Clothing'?'pieces':'cars'}`;
  document.querySelector('#empty-state').hidden=items.length!==0;
  bindDetailButtons();
}
function setKindOptions(){const select=document.querySelector('#collection-kind'); if(!select)return; const kinds=[...new Set(currentList().map(x=>x.kind))];select.innerHTML='<option>All</option>'+kinds.map(x=>`<option>${escapeHTML(x)}</option>`).join('');select.value='All';state.kind='All';}
function bindDetailButtons(){document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>openDetail(b.dataset.detail)));}

function openDetail(id){
  const x=[...getItems('estate'),...getItems('boutique'),...getItems('car')].find(i=>i.id===id);
  if(!x)return;
  state.selected=x;state.selectedSize='';
  const isEstate=page==='estate';
  const sizes=x.sizes?.length?`<div class="size-picker"><span>SELECT A SIZE TO ASK ABOUT</span><div>${x.sizes.map(size=>`<button type="button" data-size="${escapeHTML(size)}" aria-pressed="false">${escapeHTML(size)}</button>`).join('')}</div><small>Fit and availability are confirmed by phone.</small></div>`:'';
  const secondary=x.detail?`<div><small>${isEstate?'SPACE':'DETAILS'}</small><strong>${escapeHTML(x.detail)}</strong></div>`:'';
  document.querySelector('#detail-content').innerHTML=`<div class="detail-photo">${img(x.image,x.title)}</div><div class="detail-copy"><p class="eyebrow">${escapeHTML(x.kind)} / ${isEstate?escapeHTML(x.intent||'Sale'):'THE COLLECTION'}</p><h2>${escapeHTML(x.title)}</h2><p class="detail-description">${escapeHTML(x.description||'More details coming soon.')}</p><div class="detail-facts"><div><small>PRICE</small><strong>${escapeHTML(x.price)}</strong></div>${secondary}${x.location?`<div><small>LOCATION</small><strong>${escapeHTML(x.location)}</strong></div>`:''}</div>${sizes}<button class="button button-dark" id="detail-enquire">Request a call <span>↗</span></button><p class="micro-copy">${isEstate?'Visits are arranged after a call.':'Ask about size, fit or availability.'}</p></div>`;
  document.querySelector('#detail-dialog').showModal();
  document.querySelectorAll('[data-size]').forEach(button=>button.addEventListener('click',()=>{state.selectedSize=button.dataset.size;document.querySelectorAll('[data-size]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}));
  document.querySelector('#detail-enquire').addEventListener('click',()=>{document.querySelector('#detail-dialog').close();openEnquiry(x);});
}
function openEnquiry(item){state.selected=item||null;if(!item)state.selectedSize='';const dialog=document.querySelector('#enquiry-dialog');const form=document.querySelector('#enquiry-form');form.reset();form.hidden=false;document.querySelector('#enquiry-success').hidden=true;document.querySelector('#form-error').textContent='';form.querySelector('[name=item]').value=item?.title||'';form.elements.note.value=item?`I would like to know more about ${item.title}${state.selectedSize?` in size ${state.selectedSize}`:''}.`:'';dialog.showModal();}

function setupEnquiry(){
  document.querySelectorAll('[data-open-enquiry]').forEach(b=>b.addEventListener('click',()=>openEnquiry()));
  document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));
  document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d)d.close();}));
  const form=document.querySelector('#enquiry-form');
  form?.addEventListener('submit',e=>{
    e.preventDefault();
    const values=Object.fromEntries(new FormData(form));
    values.consent=form.elements.consent.checked;
    const errors=validateEnquiry(values);
    if(Object.keys(errors).length){document.querySelector('#form-error').textContent=Object.values(errors).join(' ');return;}
    const entry={name:values.name.trim(),phone:values.phone.trim(),note:values.note.trim(),item:values.item,createdAt:new Date().toISOString()};
    const all=readDemoEnquiries();all.push(entry);saveDemoEnquiries(all);
    form.hidden=true;
    const success=document.querySelector('#enquiry-success');success.hidden=false;
    success.innerHTML='<div class="success-mark">✓</div><h3>Request saved in this preview</h3><p>This demo saved your request on this device. It will reach the business only after a backend or WhatsApp number is connected.</p>';
  });
  document.querySelector('#whatsapp-button')?.addEventListener('click',()=>{
    const itemText=state.selected?`${state.selected.title}${state.selectedSize?` in size ${state.selectedSize}`:''}`:'';
    const message=itemText?`Hello, I would like a call about ${itemText}.`:'Hello, I would like to request a call.';
    const url=whatsappURL(BUSINESS_WHATSAPP,message);
    if(url)window.open(url,'_blank','noopener,noreferrer');
    else document.querySelector('#form-error').textContent='Add the business WhatsApp number in src/core.mjs to activate this link.';
  });
}

function setupCommon(){document.body.dataset.style=state.style;document.querySelectorAll('[data-style]').forEach(b=>b.addEventListener('click',()=>{state.style=b.dataset.style;localStorage.setItem('rs-style',state.style);document.body.dataset.style=state.style;document.querySelectorAll('[data-style]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.style===state.style)));}));document.querySelector('.mobile-menu')?.addEventListener('click',e=>{const open=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',String(open));document.querySelector('.site-header nav').classList.toggle('open',open);});setupEnquiry();}

app.innerHTML=page==='estate'?estatePage():page==='boutique'?boutiquePage():home();setupCommon();
if(page==='estate'){refreshCards();document.querySelectorAll('[data-quick-intent],[data-quick-kind]').forEach(b=>b.addEventListener('click',()=>{state.intent=b.dataset.quickIntent||'All';state.kind=b.dataset.quickKind||'All';document.querySelector('#estate-kind').value=state.kind;document.querySelectorAll('[data-intent]').forEach(x=>x.classList.toggle('active',x.dataset.intent===state.intent));refreshCards();document.querySelector('#listings').scrollIntoView({behavior:'smooth'});}));document.querySelectorAll('[data-intent]').forEach(b=>b.addEventListener('click',()=>{state.intent=b.dataset.intent;document.querySelectorAll('[data-intent]').forEach(x=>x.classList.toggle('active',x===b));refreshCards();}));document.querySelector('#estate-kind').addEventListener('change',e=>{state.kind=e.target.value;refreshCards();});document.querySelector('#estate-search').addEventListener('input',e=>{state.search=e.target.value;refreshCards();});}
if(page==='boutique'){setKindOptions();refreshCards();document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{state.category=b.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>x.classList.toggle('active',x===b));setKindOptions();refreshCards();}));document.querySelector('#collection-kind').addEventListener('change',e=>{state.kind=e.target.value;refreshCards();});document.querySelector('#collection-search').addEventListener('input',e=>{state.search=e.target.value;refreshCards();});}
