import {createServer} from 'node:http';
import {readFile, mkdir, writeFile, stat} from 'node:fs/promises';
import {createReadStream} from 'node:fs';
import {resolve, extname, sep} from 'node:path';
import {randomUUID} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {estate,boutique,cars} from './data.mjs';
import {validateEnquiry,validateListing,cleanText} from './core.mjs';
import {createSheetDelivery} from './sheets.mjs';
import {pageSEO,sitemapXML} from './seo.mjs';
import {legacyFeatureItems,validateFeatureItems,cleanFeatureItems} from './features.mjs';

const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.js':'text/javascript; charset=utf-8','.jpg':'image/jpeg','.png':'image/png','.webp':'image/webp','.mp4':'video/mp4','.webm':'video/webm','.mov':'video/quicktime'};
const stories=[
 {id:'plot-guide',date:'2026-09-12',image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1100&q=85',title:'What to check before buying a plot',titleTe:'ప్లాట్ కొనుగోలు ముందు పరిశీలించాల్సినవి',summary:'A practical checklist for location, access, approvals and documents.',summaryTe:'ప్రాంతం, రాకపోకలు, అనుమతులు, పత్రాల కోసం ఉపయోగకరమైన జాబితా.',body:'Start with the survey number and ownership documents. Confirm road access, zoning, approvals and utilities with the relevant authorities. Visit the plot and ask for every promise in writing.',bodyTe:'ముందుగా సర్వే నంబర్, యాజమాన్య పత్రాలు పరిశీలించండి. రహదారి సౌకర్యం, భూమి వినియోగం, అనుమతులు, నీరు మరియు విద్యుత్ గురించి సంబంధిత అధికారులతో నిర్ధారించుకోండి. స్థలాన్ని సందర్శించి ప్రతి హామీని రాతపూర్వకంగా పొందండి.'},
 {id:'rent-guide',date:'2026-08-28',image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1100&q=85',title:'A calmer way to shortlist a rental',titleTe:'అద్దె ఇంటిని సులభంగా ఎంపిక చేసుకునే విధానం',summary:'Compare the complete monthly cost and daily commute before visiting.',summaryTe:'ఇల్లు చూసే ముందు మొత్తం నెలవారీ ఖర్చు, ప్రయాణ సమయాన్ని పోల్చండి.',body:'Look beyond the listed rent. Note maintenance, deposit, parking, utilities and travel time. Shortlist a few homes, then request a call to confirm availability and arrange visits.',bodyTe:'ప్రకటనలో ఉన్న అద్దెతో పాటు నిర్వహణ ఖర్చు, డిపాజిట్, పార్కింగ్, సౌకర్యాలు, ప్రయాణ సమయం కూడా లెక్కించండి. కొన్ని ఇళ్లను ఎంపిక చేసి అందుబాటును నిర్ధారించడానికి కాల్ కోరండి.'},
 {id:'visit-guide',date:'2026-08-03',image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1100&q=85',title:'Questions to take to a property visit',titleTe:'ఇల్లు చూసేటప్పుడు అడగాల్సిన ప్రశ్నలు',summary:'A viewing checklist that makes comparisons easier later.',summaryTe:'తరువాత పోల్చుకోవడానికి ఉపయోగపడే పరిశీలన జాబితా.',body:'Check daylight, ventilation, water supply and shared spaces. Ask about maintenance, documents and handover. Photograph details with the owner’s permission.',bodyTe:'సహజ వెలుతురు, గాలి, నీటి సరఫరా, ఉమ్మడి ప్రదేశాల స్థితిని పరిశీలించండి. నిర్వహణ, పత్రాలు, అప్పగించే సమయం గురించి అడగండి. యజమాని అనుమతితో వివరాలను ఫోటోలు తీసుకోండి.'},
 {id:'vizag-market-guide',date:'2026-10-03',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?w=1100&q=85',title:'How to read the Vizag property market',titleTe:'విశాఖ ఆస్తి మార్కెట్‌ను ఎలా అర్థం చేసుకోవాలి',summary:'Compare actual homes and plots, total costs and travel times before believing a price trend.',summaryTe:'ధరల ధోరణిని నమ్మే ముందు నిజమైన ఆస్తులు, మొత్తం ఖర్చు, ప్రయాణ సమయాన్ని పోల్చండి.',body:'A citywide average cannot tell you whether one street or project fits your needs. Start with a budget that includes registration, taxes, maintenance and any loan cost. Compare properties of the same type, size and approval status in the same locality. Ask how long each listing has been available and whether its asking price has changed.\nFor plots, check the survey number, access road, permitted use, title and applicable approvals with the relevant authority. For flats, compare carpet area, maintenance, parking, completion status and handover terms. Visit at the time of day when you will normally travel.\nMarket commentary is useful as context, not a promise of appreciation. We publish practical observations and update them when verified information is available. Ask for a call if you want help making a focused shortlist.',bodyTe:'నగరం మొత్తం సగటు ధరతో ఒక వీధి లేదా ప్రాజెక్ట్ మీకు సరిపోతుందో తెలియదు. రిజిస్ట్రేషన్, పన్నులు, నిర్వహణ, రుణ ఖర్చులు కలిపి బడ్జెట్ నిర్ణయించండి. ఒకే ప్రాంతంలో ఒకే రకం, విస్తీర్ణం, అనుమతులు ఉన్న ఆస్తులను పోల్చండి.\nప్లాట్లకు సర్వే నంబర్, రహదారి, భూమి వినియోగం, యాజమాన్య పత్రాలు, అవసరమైన అనుమతులు పరిశీలించండి. ఫ్లాట్లకు కార్పెట్ ఏరియా, నిర్వహణ, పార్కింగ్, నిర్మాణ స్థితి, అప్పగింత నిబంధనలు పోల్చండి.\nమార్కెట్ వ్యాఖ్యలు సందర్భం కోసం మాత్రమే, భవిష్యత్ ధరల హామీ కాదు. మీ అవసరాలకు తగిన ఎంపిక కోసం కాల్ కోరండి.'},
 {id:'ai-property-search',date:'2026-10-03',image:'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1100&q=85',title:'Where AI helps in a property search',titleTe:'ఆస్తి వెతుకులాటలో AI ఎక్కడ ఉపయోగపడుతుంది',summary:'Use AI to organise choices and questions. Verify prices, documents and availability yourself.',summaryTe:'ఎంపికలు, ప్రశ్నలు క్రమబద్ధం చేయడానికి AI ఉపయోగించండి. ధరలు, పత్రాలు, అందుబాటును స్వయంగా నిర్ధారించండి.',body:'AI can turn a long list of property descriptions into a comparison table and help you draft questions for a site visit. It can also estimate commute scenarios when you supply actual routes and timings. These are planning aids, not evidence that a listing is available or legally clear.\nAsk the seller or agent for current photos, exact location, area measurements, ownership records and approval details. Check official records and use an independent qualified professional for legal or financial decisions. Never upload identity documents or bank details to an untrusted AI tool.\nA useful prompt is: Compare these three listings by total cost, usable area, commute and missing information. Show what I still need to verify. That keeps the conversation focused on facts that can be checked.',bodyTe:'AI ద్వారా అనేక ఆస్తి వివరాలను పోలిక పట్టికగా మార్చుకోవచ్చు. స్థల సందర్శనలో అడగాల్సిన ప్రశ్నలను కూడా సిద్ధం చేసుకోవచ్చు. ఇవి ప్రణాళికకు సహాయం మాత్రమే. ప్రకటన అందుబాటులో ఉందని లేదా పత్రాలు సరిగా ఉన్నాయని రుజువు కాదు.\nప్రస్తుత ఫోటోలు, ఖచ్చితమైన స్థలం, విస్తీర్ణం, యాజమాన్య పత్రాలు, అనుమతులు అడగండి. అధికారిక రికార్డులు పరిశీలించి ముఖ్యమైన నిర్ణయాలకు స్వతంత్ర నిపుణుడిని సంప్రదించండి. గుర్తింపు పత్రాలు, బ్యాంకు వివరాలను నమ్మదగని AI సాధనంలో అప్‌లోడ్ చేయవద్దు.\nమూడు ప్రకటనలను మొత్తం ఖర్చు, ఉపయోగించగల విస్తీర్ణం, ప్రయాణం, లేని సమాచారం ప్రకారం పోల్చమని AIని అడగండి. తరువాత ప్రతి ముఖ్యమైన విషయాన్ని స్వయంగా నిర్ధారించండి.'}
];
const extra={e1:['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1100&q=85','https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1100&q=85'],b1:['https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=900&q=85'],c1:['https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1000&q=85']};
const send=(res,status,value)=>res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}).end(JSON.stringify(value));
async function readBody(req){let size=0;const chunks=[];for await(const c of req){size+=c.length;if(size>8e6)throw {status:413,message:'Request too large'};chunks.push(c);}try{return JSON.parse(Buffer.concat(chunks).toString())}catch{throw {status:400,message:'Invalid JSON'}}}
async function readBytes(req,limit){let size=0;const chunks=[];for await(const c of req){size+=c.length;if(size>limit)throw {status:413,message:'Video is too large'};chunks.push(c)}return Buffer.concat(chunks)}
function validImageBytes(bytes,kind){if(kind==='jpeg')return bytes.length>=3&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;if(kind==='png')return bytes.length>=8&&bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));return kind==='webp'&&bytes.length>=12&&bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP'}
export function createBackend({dbPath=':memory:',staticRoot=resolve(import.meta.dirname,'..'),adminToken=process.env.ADMIN_TOKEN||'',sheetUrl=process.env.GOOGLE_SHEETS_WEBHOOK_URL||'',sheetSecret=process.env.GOOGLE_SHEETS_SECRET||'',siteUrl=process.env.SITE_URL||'',publishReady=process.env.PUBLISH_READY==='true',siteVariant=process.env.SITE_VARIANT||'all',fetcher=fetch}={}){
 siteVariant=['estate','boutique'].includes(siteVariant)?siteVariant:'all';
 const visibleSections=siteVariant==='estate'?['estate']:siteVariant==='boutique'?['boutique','car']:['estate','boutique','car'];
 const db=new DatabaseSync(dbPath);db.exec('PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS listings(id TEXT PRIMARY KEY,section TEXT,data TEXT,updated TEXT);CREATE TABLE IF NOT EXISTS editorials(id TEXT PRIMARY KEY,data TEXT,updated TEXT);CREATE TABLE IF NOT EXISTS reviews(id TEXT PRIMARY KEY,listing_id TEXT,data TEXT,status TEXT,created TEXT);CREATE TABLE IF NOT EXISTS enquiries(id TEXT PRIMARY KEY,data TEXT,created TEXT);CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT)');
 const delivery=createSheetDelivery(db,{url:sheetUrl,secret:sheetSecret,fetcher});
 const subscribers=new Set();
 const announce=section=>{for(const res of subscribers)res.write(`event: content\ndata: ${JSON.stringify({section,at:Date.now()})}\n\n`)};
 const all=(table,where='',args=[])=>db.prepare(`SELECT data FROM ${table} ${where}`).all(...args).map(x=>JSON.parse(x.data));
 const visibleListings=()=>all('listings','ORDER BY updated DESC').filter(x=>visibleSections.includes(x.section));
 if(!db.prepare('SELECT value FROM meta WHERE key=?').get('listings-seeded')){if(!db.prepare('SELECT COUNT(*) n FROM listings').get().n){const insert=db.prepare('INSERT INTO listings VALUES(?,?,?,?)');for(const [section,items] of [['estate',estate],['boutique',boutique],['car',cars]])for(const x of items)insert.run(x.id,section,JSON.stringify({...x,section,photos:[x.image,...(extra[x.id]||[])]}),new Date().toISOString());}db.prepare('INSERT INTO meta VALUES(?,?)').run('listings-seeded','1');}
 if(!db.prepare('SELECT value FROM meta WHERE key=?').get('car-rental-sample-v1')){if(!db.prepare('SELECT id FROM listings WHERE id=?').get('c3')){const x=cars.find(item=>item.id==='c3');db.prepare('INSERT INTO listings VALUES(?,?,?,?)').run(x.id,'car',JSON.stringify({...x,section:'car',photos:[x.image],videos:[]}),new Date().toISOString());}db.prepare('INSERT INTO meta VALUES(?,?)').run('car-rental-sample-v1','1');}
 if(!db.prepare('SELECT value FROM meta WHERE key=?').get('car-telugu-v1')){for(const sample of cars){const row=db.prepare('SELECT data FROM listings WHERE id=?').get(sample.id);if(!row)continue;const item=JSON.parse(row.data);for(const field of ['titleTe','detailTe','descriptionTe','locationTe'])if(!item[field]&&sample[field])item[field]=sample[field];db.prepare('UPDATE listings SET data=? WHERE id=?').run(JSON.stringify(item),sample.id)}db.prepare('INSERT INTO meta VALUES(?,?)').run('car-telugu-v1','1');}
 for(const id of ['b1','b2','b4']){const found=db.prepare('SELECT data FROM listings WHERE id=?').get(id);if(found){const item=JSON.parse(found.data);if(item.topSeller===undefined){item.topSeller=true;db.prepare('UPDATE listings SET data=? WHERE id=?').run(JSON.stringify(item),id)}}}
 if(!db.prepare('SELECT value FROM meta WHERE key=?').get('editorials-seeded')){if(!db.prepare('SELECT COUNT(*) n FROM editorials').get().n){const insert=db.prepare('INSERT INTO editorials VALUES(?,?,?)');for(const x of stories)insert.run(x.id,JSON.stringify(x),new Date().toISOString());}db.prepare('INSERT INTO meta VALUES(?,?)').run('editorials-seeded','1');}
 if(!db.prepare('SELECT value FROM meta WHERE key=?').get('vizag-samples-v1')){const oldTitles=['The Courtyard Residence','The Skyline Apartment','The Palm House','The Garden Apartment','The Open Plot','The Work Loft'];for(const [index,sample] of estate.entries()){const row=db.prepare('SELECT data FROM listings WHERE id=?').get(sample.id);if(!row)continue;const item=JSON.parse(row.data);if(item.title!==oldTitles[index])continue;const photos=[sample.image,...(extra[sample.id]||[])];db.prepare('UPDATE listings SET data=?,updated=? WHERE id=?').run(JSON.stringify({...item,...sample,section:'estate',photos}),new Date().toISOString(),sample.id)}for(const sample of stories.filter(x=>['vizag-market-guide','ai-property-search'].includes(x.id))){if(!db.prepare('SELECT id FROM editorials WHERE id=?').get(sample.id))db.prepare('INSERT INTO editorials VALUES(?,?,?)').run(sample.id,JSON.stringify(sample),new Date().toISOString())}db.prepare('INSERT INTO meta VALUES(?,?)').run('vizag-samples-v1','1');}
 if(!db.prepare('SELECT value FROM meta WHERE key=?').get('estate-detail-v1')){for(const sample of estate){const row=db.prepare('SELECT data FROM listings WHERE id=?').get(sample.id);if(!row){if(sample.id==='e7')db.prepare('INSERT INTO listings VALUES(?,?,?,?)').run(sample.id,'estate',JSON.stringify({...sample,section:'estate',photos:[sample.image]}),new Date().toISOString());continue}const item=JSON.parse(row.data);if(item.title===sample.title&&!item.amenities)db.prepare('UPDATE listings SET data=?,updated=? WHERE id=?').run(JSON.stringify({...item,amenities:sample.amenities,amenitiesTe:sample.amenitiesTe}),new Date().toISOString(),sample.id)}db.prepare('INSERT INTO meta VALUES(?,?)').run('estate-detail-v1','1');}
 if(!db.prepare('SELECT value FROM meta WHERE key=?').get('bilingual-features-v1')){for(const row of db.prepare('SELECT id,data FROM listings WHERE section=?').all('estate')){const item=JSON.parse(row.data);if(Array.isArray(item.amenityItems)&&Array.isArray(item.connectivityItems))continue;const updated={...item,amenityItems:Array.isArray(item.amenityItems)?item.amenityItems:legacyFeatureItems(item.amenities,item.amenitiesTe),connectivityItems:Array.isArray(item.connectivityItems)?item.connectivityItems:legacyFeatureItems(item.connectivity,item.connectivityTe)};db.prepare('UPDATE listings SET data=? WHERE id=?').run(JSON.stringify(updated),row.id)}db.prepare('INSERT INTO meta VALUES(?,?)').run('bilingual-features-v1','1');}
 if(!db.prepare('SELECT value FROM meta WHERE key=?').get('boutique-specs-v1')){for(const sample of boutique.filter(x=>x.material)){const row=db.prepare('SELECT data FROM listings WHERE id=?').get(sample.id);if(!row)continue;const item=JSON.parse(row.data);if(item.title===sample.title&&!item.material)db.prepare('UPDATE listings SET data=? WHERE id=?').run(JSON.stringify({...item,material:sample.material,fit:sample.fit,care:sample.care}),sample.id)}db.prepare('INSERT INTO meta VALUES(?,?)').run('boutique-specs-v1','1');}
 const handler=async(req,res)=>{try{const u=new URL(req.url,'http://localhost');const p=decodeURIComponent(u.pathname),m=req.method;
 if(p.startsWith('/api/')){
  if(p==='/api/health'&&m==='GET')return send(res,200,{ok:true});
  if(p==='/api/site-config'&&m==='GET')return send(res,200,{variant:siteVariant,sections:visibleSections});
  if(p==='/api/settings'&&m==='GET')return send(res,200,JSON.parse(db.prepare('SELECT value FROM meta WHERE key=?').get('site-settings')?.value||'{}'));
  if(p==='/api/events'&&m==='GET'){res.writeHead(200,{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Content-Type-Options':'nosniff'});res.write(': connected\n\n');subscribers.add(res);const heartbeat=setInterval(()=>res.write(': heartbeat\n\n'),25000);heartbeat.unref();req.on('close',()=>{clearInterval(heartbeat);subscribers.delete(res)});return;}
  if(p==='/api/listings'&&m==='GET')return send(res,200,visibleListings().filter(x=>!u.searchParams.has('section')||x.section===u.searchParams.get('section')));
  if(p==='/api/editorials'&&m==='GET')return send(res,200,siteVariant==='boutique'?[]:all('editorials','ORDER BY updated DESC'));
  if(p==='/api/reviews'&&m==='GET')return send(res,200,siteVariant==='estate'?[]:all('reviews',u.searchParams.has('listing')?'WHERE listing_id=? AND status=? ORDER BY created DESC':'WHERE status=? ORDER BY created DESC',u.searchParams.has('listing')?[u.searchParams.get('listing'),'approved']:['approved']));
  if(p==='/api/enquiries'&&m==='POST'){const v=await readBody(req),errors=validateEnquiry(v);if(Object.keys(errors).length)return send(res,400,{errors});if(!visibleSections.includes(v.source||'estate'))return send(res,400,{error:'Choose a section available on this website.'});const x={id:randomUUID(),name:cleanText(v.name,100)||'Website visitor',phone:cleanText(v.phone,25),note:cleanText([v.goal?`Goal: ${cleanText(v.goal,30)}`:'',v.area?`Area: ${cleanText(v.area,100)}`:'',v.budget?`Budget: ${cleanText(v.budget,80)}`:'',v.note?`Message: ${cleanText(v.note,500)}`:''].filter(Boolean).join(' | '),700),goal:cleanText(v.goal,30),area:cleanText(v.area,100),budget:cleanText(v.budget,80),item:cleanText(v.item,100),itemId:cleanText(v.itemId,80),source:['estate','boutique','car'].includes(v.source)?v.source:'estate',consent:true,sheetStatus:delivery.status().configured?'pending':'not_configured',createdAt:new Date().toISOString()};db.prepare('INSERT INTO enquiries VALUES(?,?,?)').run(x.id,JSON.stringify(x),x.createdAt);send(res,201,{id:x.id,sheetStatus:x.sheetStatus});if(delivery.status().configured)void delivery.syncOne(x.id);return;}
  if(p==='/api/reviews'&&m==='POST'){if(siteVariant==='estate')return send(res,403,{error:'Reviews are available on the boutique website.'});const v=await readBody(req),rating=Number(v.rating),code=cleanText(v.reviewCode,80);if(!db.prepare('SELECT id FROM listings WHERE id=? AND section=?').get(v.listingId,'boutique')||!Number.isInteger(rating)||rating<1||rating>5||!cleanText(v.name,70)||!cleanText(v.comment,1000)||!code)return send(res,400,{error:'Add a clothing item, name, rating, comment and review code.'});const purchase=all('enquiries').find(item=>item.source==='boutique'&&item.itemId===v.listingId&&item.reviewCode===code&&!item.reviewUsedAt);if(!purchase)return send(res,403,{error:'A review code from a verified purchase is required.'});const x={id:randomUUID(),listingId:v.listingId,name:cleanText(v.name,70),rating,comment:cleanText(v.comment,1000),createdAt:new Date().toISOString(),status:'pending',verifiedPurchase:true};db.prepare('INSERT INTO reviews VALUES(?,?,?,?,?)').run(x.id,x.listingId,JSON.stringify(x),'pending',x.createdAt);db.prepare('UPDATE enquiries SET data=? WHERE id=?').run(JSON.stringify({...purchase,reviewUsedAt:x.createdAt}),purchase.id);return send(res,201,{id:x.id,status:'pending'});}
  if(adminToken&&req.headers['x-admin-token']!==adminToken)return send(res,401,{error:'Admin token required.'});
  if(p==='/api/settings'&&m==='PUT'){const v=await readBody(req),url=value=>{const result=cleanText(value,300);return /^https?:\/\//i.test(result)?result:''},settings={phone:cleanText(v.phone,30),email:cleanText(v.email,120),address:cleanText(v.address,200),whatsapp:String(v.whatsapp||'').replace(/\D/g,'').slice(0,15),instagram:url(v.instagram),facebook:url(v.facebook),youtube:url(v.youtube)};db.prepare('INSERT INTO meta VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run('site-settings',JSON.stringify(settings));announce('settings');return send(res,200,settings)}
  if(p==='/api/admin/enquiries'&&m==='GET')return send(res,200,all('enquiries','ORDER BY created DESC').filter(x=>visibleSections.includes(x.source)));
  if(p.startsWith('/api/admin/enquiries/')&&p.endsWith('/review-invite')&&m==='POST'){if(siteVariant==='estate')return send(res,403,{error:'Reviews are available on the boutique website.'});const id=p.split('/')[4],row=db.prepare('SELECT data FROM enquiries WHERE id=?').get(id);if(!row)return send(res,404,{error:'Call request not found.'});const item=JSON.parse(row.data);if(item.source!=='boutique'||!item.itemId||!db.prepare('SELECT id FROM listings WHERE id=? AND section=?').get(item.itemId,'boutique'))return send(res,400,{error:'Only a boutique item request can receive a review code.'});const reviewCode=item.reviewCode||randomUUID();db.prepare('UPDATE enquiries SET data=? WHERE id=?').run(JSON.stringify({...item,reviewCode}),id);return send(res,200,{reviewCode,itemId:item.itemId});}
  if(p==='/api/admin/sheets'&&m==='GET')return send(res,200,delivery.status());
  if(p==='/api/admin/sheets/sync'&&m==='POST')return send(res,200,await delivery.syncPending());
  if(p==='/api/admin/reviews'&&m==='GET')return send(res,200,siteVariant==='estate'?[]:all('reviews','ORDER BY created DESC'));
  if(p==='/api/listings'&&['POST','PUT'].includes(m)){const v=await readBody(req),errors=validateListing(v);if(Object.keys(errors).length)return send(res,400,{errors});if(!visibleSections.includes(v.section))return send(res,403,{error:'This section is not available on this website.'});if(!Array.isArray(v.photos)||v.photos.length>12||v.photos.some(x=>typeof x!=='string'||!(/^(https?:\/\/|\/uploads\/)/.test(x))))return send(res,400,{error:'Add up to 12 image URLs.'});if(v.videos!==undefined&&(!Array.isArray(v.videos)||v.videos.length>4||v.videos.some(x=>typeof x!=='string'||!(/^(https?:\/\/|\/uploads\/)/.test(x)))))return send(res,400,{error:'Add up to 4 video URLs.'});for(const field of ['amenityItems','connectivityItems'])if(v[field]!==undefined&&!validateFeatureItems(v[field]))return send(res,400,{error:`${field} must contain up to 60 English and Telugu label pairs.`});for(const [modern,legacy,translated] of [['amenityItems','amenities','amenitiesTe'],['connectivityItems','connectivity','connectivityTe']])if(!validateFeatureItems(v[modern]??legacyFeatureItems(v[legacy],v[translated])))return send(res,400,{error:'Use up to 60 English and Telugu feature pairs.'});const x={...v,id:cleanText(v.id,80)||randomUUID(),title:cleanText(v.title,100),titleTe:cleanText(v.titleTe,100),kindTe:cleanText(v.kindTe,60),description:cleanText(v.description,2000),descriptionTe:cleanText(v.descriptionTe,2000),locationTe:cleanText(v.locationTe,100),amenityItems:cleanFeatureItems(v.amenityItems||legacyFeatureItems(v.amenities,v.amenitiesTe)),connectivityItems:cleanFeatureItems(v.connectivityItems||legacyFeatureItems(v.connectivity,v.connectivityTe)),videos:v.videos||[],material:cleanText(v.material,160),fit:cleanText(v.fit,160),care:cleanText(v.care,160),mapQuery:cleanText(v.mapQuery,200),topSeller:Boolean(v.topSeller),image:v.photos[0]||''};db.prepare('INSERT INTO listings VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET section=excluded.section,data=excluded.data,updated=excluded.updated').run(x.id,x.section,JSON.stringify(x),new Date().toISOString());announce(x.section);return send(res,200,x);}
  if(p.startsWith('/api/listings/')&&m==='DELETE'){const id=p.split('/').pop(),old=db.prepare('SELECT section FROM listings WHERE id=?').get(id);if(old&&!visibleSections.includes(old.section))return send(res,403,{error:'This section is not available on this website.'});db.prepare('DELETE FROM listings WHERE id=?').run(id);if(old)announce(old.section);return send(res,200,{ok:true});}
  if(p==='/api/editorials'&&['POST','PUT'].includes(m)){if(siteVariant==='boutique')return send(res,403,{error:'Editorials are available on the estate website.'});const v=await readBody(req);if(!cleanText(v.title,150)||!cleanText(v.body,10000))return send(res,400,{error:'Add a title and article text.'});const x={id:cleanText(v.id,80)||randomUUID(),date:cleanText(v.date,20),image:cleanText(v.image,500),title:cleanText(v.title,150),titleTe:cleanText(v.titleTe,150),summary:cleanText(v.summary,500),summaryTe:cleanText(v.summaryTe,500),body:cleanText(v.body,10000),bodyTe:cleanText(v.bodyTe,10000)};db.prepare('INSERT INTO editorials VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data,updated=excluded.updated').run(x.id,JSON.stringify(x),new Date().toISOString());announce('editorials');return send(res,200,x);}
  if(p.startsWith('/api/editorials/')&&m==='DELETE'){if(siteVariant==='boutique')return send(res,403,{error:'Editorials are available on the estate website.'});db.prepare('DELETE FROM editorials WHERE id=?').run(p.split('/').pop());announce('editorials');return send(res,200,{ok:true});}
  if(p.startsWith('/api/admin/reviews/')&&m==='PATCH'){if(siteVariant==='estate')return send(res,403,{error:'Reviews are available on the boutique website.'});const id=p.split('/').pop(),v=await readBody(req);if(!['approved','rejected'].includes(v.status))return send(res,400,{error:'Invalid status.'});const old=db.prepare('SELECT data FROM reviews WHERE id=?').get(id);if(!old)return send(res,404,{error:'Review not found.'});const x={...JSON.parse(old.data),status:v.status};db.prepare('UPDATE reviews SET data=?,status=? WHERE id=?').run(JSON.stringify(x),v.status,id);announce('boutique');return send(res,200,x);}
  if(p==='/api/uploads'&&m==='POST'){const v=await readBody(req),match=/^data:image\/(jpeg|png|webp);base64,([A-Za-z0-9+/=]+)$/.exec(v.data||'');if(!match)return send(res,400,{error:'Use a JPEG, PNG or WebP image.'});const bytes=Buffer.from(match[2],'base64');if(bytes.length>4e6)return send(res,413,{error:'Image is too large.'});if(!validImageBytes(bytes,match[1]))return send(res,400,{error:'The file does not match its image format.'});const name=`${randomUUID()}.${match[1]==='jpeg'?'jpg':match[1]}`;await mkdir(resolve(staticRoot,'uploads'),{recursive:true});await writeFile(resolve(staticRoot,'uploads',name),bytes);return send(res,201,{url:`/uploads/${name}`});}
  if(p==='/api/media'&&m==='POST'){const kind=req.headers['content-type'];const extension=({'video/mp4':'mp4','video/webm':'webm','video/quicktime':'mov'})[kind];if(!extension)return send(res,400,{error:'Use an MP4, WebM or MOV video.'});const bytes=await readBytes(req,100*1024*1024);const valid=kind==='video/webm'?bytes.subarray(0,4).equals(Buffer.from([0x1a,0x45,0xdf,0xa3])):bytes.toString('ascii',4,8)==='ftyp';if(!valid)return send(res,400,{error:'The file does not match its video format.'});const name=`${randomUUID()}.${extension}`;await mkdir(resolve(staticRoot,'uploads'),{recursive:true});await writeFile(resolve(staticRoot,'uploads',name),bytes);return send(res,201,{url:`/uploads/${name}`});}
  return send(res,404,{error:'API route not found.'});
 }
 if(!['GET','HEAD'].includes(m))return send(res,405,{error:'Method not allowed.'});
 if(siteVariant==='estate'&&['/boutique.html','/collection.html','/cars.html'].includes(p)||siteVariant==='boutique'&&['/estate.html','/properties.html','/property.html','/editorials.html','/article.html','/about.html'].includes(p))return send(res,404,{error:'Page not found on this website.'});
 if(p==='/robots.txt'){const body=`User-agent: *\nDisallow: /admin.html\nDisallow: /api/\n${publishReady&&siteUrl?`Sitemap: ${siteUrl.replace(/\/$/,'')}/sitemap.xml\n`:'Disallow: /\n'}`;return res.writeHead(200,{'Content-Type':'text/plain; charset=utf-8'}).end(m==='HEAD'?undefined:body)}
 if(p==='/sitemap.xml'){const body=sitemapXML({siteUrl,publishReady,listings:visibleListings(),editorials:siteVariant==='boutique'?[]:all('editorials'),variant:siteVariant});return res.writeHead(200,{'Content-Type':'application/xml; charset=utf-8'}).end(m==='HEAD'?undefined:body)}
 const file=resolve(staticRoot,p==='/'?'index.html':'.'+p);if(file!==staticRoot&&!file.startsWith(staticRoot+sep)||p.split('/').some(part=>part.startsWith('.'))||p.startsWith('/data/')||p.startsWith('/tests/')||p.includes('.sqlite'))return send(res,403,{error:'Forbidden.'});
 const type=mime[extname(file)]||'application/octet-stream';
 if(type.startsWith('video/')){
  const size=(await stat(file)).size;let start=0,end=size-1,status=200;
  if(req.headers.range){const match=/^bytes=(\d*)-(\d*)$/.exec(req.headers.range);if(!match||(!match[1]&&!match[2]))return res.writeHead(416,{'Content-Range':`bytes */${size}`}).end();if(!match[1]){start=Math.max(0,size-Number(match[2]));}else{start=Number(match[1]);if(match[2])end=Number(match[2]);}if(start>=size||end>=size||start>end)return res.writeHead(416,{'Content-Range':`bytes */${size}`}).end();status=206;}
  const headers={'Content-Type':type,'X-Content-Type-Options':'nosniff','Accept-Ranges':'bytes','Content-Length':end-start+1};if(status===206)headers['Content-Range']=`bytes ${start}-${end}/${size}`;res.writeHead(status,headers);if(m==='HEAD')res.end();else createReadStream(file,{start,end}).pipe(res);return;
 }
 let content=await readFile(file);if(type.startsWith('text/html')&&['/','/index.html','/estate.html','/properties.html','/property.html','/editorials.html','/article.html','/about.html','/boutique.html','/collection.html','/cars.html'].includes(p)){const seo=pageSEO(p,u.searchParams,{listings:visibleListings(),editorials:siteVariant==='boutique'?[]:all('editorials'),siteUrl,publishReady,variant:siteVariant});content=Buffer.from(content.toString().replace(/<title>[^<]*<\/title>/,seo))}res.writeHead(200,{'Content-Type':type,'X-Content-Type-Options':'nosniff'}).end(m==='HEAD'?undefined:content);
 }catch(e){send(res,e.status||404,{error:e.status?e.message:'Not found.'});}};
 const server=createServer(handler);let retryTimer;server.on('listening',()=>{if(delivery.status().configured){void delivery.syncPending();retryTimer=setInterval(()=>void delivery.syncPending(),60_000);retryTimer.unref()}});server.on('close',()=>clearInterval(retryTimer));
 return {db,server,delivery};
}
