const labels={
 en:{inventory:'Inventory',about:'How it works',boutique:'Boutique',language:'Change language',eyebrow:'Sale and rental',hero:'Cars for sale and rent.',lead:'Explore the current selection. See the details, then request a call to discuss a car.',browse:'Browse cars',featured:'Featured listing',available:'Available now',availableNote:'Choose a car to see every photo, video and detail.',search:'Search make or model',all:'All cars',sale:'For sale',rent:'For rent',more:'Show more cars',view:'View car',photos:'photos',videos:'videos',steps:'A simple way to start',stepOne:'Explore',stepOneText:'Compare the listed details and media.',stepTwo:'Talk',stepTwoText:'Request a call about availability and price.',stepThree:'Visit',stepThreeText:'Arrange a visit after speaking with us.',sell:'Selling a car?',sellText:'Tell us about the make, year, condition and mileage. We will call you to discuss it.',sellCta:'Request a call',back:'Back to boutique',sample:'Sample listings and images. Replace before launch.'},
 te:{inventory:'కార్ల జాబితా',about:'మా విధానం',boutique:'బుటిక్',language:'భాష మార్చండి',eyebrow:'ఎంపిక చేసిన కార్లు',hero:'అమ్మకానికి, అద్దెకు కార్లు.',lead:'అందుబాటులో ఉన్న కార్లు, వాటి వివరాలు చూడండి. నచ్చిన కారు గురించి మాట్లాడేందుకు కాల్ కోరండి.',browse:'కార్లు చూడండి',featured:'ప్రత్యేక కారు',available:'అందుబాటులో ఉన్న కార్లు',availableNote:'అన్ని ఫోటోలు, వీడియోలు, వివరాల కోసం కారును ఎంచుకోండి.',search:'మోడల్ లేదా తయారీదారుని వెతకండి',all:'అన్ని కార్లు',sale:'అమ్మకానికి',rent:'అద్దెకు',more:'మరిన్ని కార్లు',view:'కారు చూడండి',photos:'ఫోటోలు',videos:'వీడియోలు',steps:'ప్రారంభించే విధానం',stepOne:'చూడండి',stepOneText:'కారు వివరాలు, ఫోటోలు పోల్చండి.',stepTwo:'మాట్లాడండి',stepTwoText:'అందుబాటు, ధర గురించి కాల్ కోరండి.',stepThree:'సందర్శించండి',stepThreeText:'మాట్లాడిన తర్వాత సందర్శన ఏర్పాటు చేసుకోండి.',sell:'కారును అమ్మాలనుకుంటున్నారా?',sellText:'మోడల్, సంవత్సరం, స్థితి, నడిచిన దూరం తెలియజేయండి. మాట్లాడేందుకు మేము కాల్ చేస్తాము.',sellCta:'కాల్ కోరండి',back:'బుటిక్‌కు తిరిగి వెళ్లండి',sample:'ఇవి నమూనా ప్రకటనలు, చిత్రాలు. ప్రారంభానికి ముందు మార్చండి.'}
};
const t=(lang,key)=>labels[lang]?.[key]||labels.en[key];
const title=(item,lang)=>lang==='te'?(item.titleTe||item.title):item.title;
const detail=(item,lang)=>lang==='te'?(item.detailTe||item.detail||''):(item.detail||'');
const amount=(item,lang)=>lang==='te'&&item.price==='Price on request'?'ధర కోసం సంప్రదించండి':item.price;
const category=(item,lang)=>lang==='te'?(item.kindTe||{'Pre-owned':'వాడిన కార్లు',Rental:'అద్దె కార్లు'}[item.kind]||item.kind):item.kind;

export function motorPage({lang,listings,pic,esc,dialogs}){
 const featured=listings.find(item=>item.section==='car'&&item.intent!=='Rent')||listings.find(item=>item.section==='car');
 const photo=featured?.photos?.[0]||featured?.image||'';
 const kinds=[...new Set(listings.filter(item=>item.section==='car').map(item=>item.kind))];
 return `<header class="car-header"><a class="car-brand" href="/cars.html"><span class="car-brand-mark">RS<span class="car-brand-dot">.</span></span><span>${lang==='te'?'మోటార్<br><small>సేకరణ</small>':'MOTOR<br><small>COLLECTION</small>'}</span></a><nav aria-label="${lang==='te'?'కారు మెను':'Car navigation'}"><a href="#inventory">${t(lang,'inventory')}</a><a href="#approach">${t(lang,'about')}</a><a href="/boutique.html">${t(lang,'boutique')} ↗</a></nav><div class="header-actions"><button class="language-button" id="language" aria-label="${t(lang,'language')}">${lang==='en'?'తెలుగు':'English'}</button><button class="mobile-menu" aria-label="${lang==='te'?'మెను తెరవండి':'Open menu'}" aria-expanded="false">☰</button></div></header>
 <main><section class="motor-hero"><div class="motor-hero-copy"><span class="motor-index">01 / RS ${lang==='te'?'మోటార్':'MOTOR'}</span><p class="motor-kicker">${t(lang,'eyebrow')}</p><h1>${t(lang,'hero')}</h1><p class="motor-lead">${t(lang,'lead')}</p><a class="motor-cta" href="#inventory">${t(lang,'browse')} <span>↗</span></a><div class="motor-hero-rule"><span>${lang==='te'?'అమ్మకం':'SALE'}</span><span>${lang==='te'?'అద్దె':'RENTAL'}</span><span>2026</span></div></div><div class="motor-hero-visual"><div class="motor-image-wrap">${pic(photo,featured?title(featured,lang):lang==='te'?'కారు':'Car')}</div><div class="motor-photo-caption"><span>${t(lang,'featured')}</span><strong>${esc(featured?title(featured,lang):'')}</strong><small>${esc(featured?detail(featured,lang):'')}</small></div><span class="motor-visual-index">RS / 01</span></div></section>
 <section id="inventory" class="motor-inventory"><div class="motor-section-head" data-reveal><div><span class="motor-index">02 / ${t(lang,'inventory')}</span><h2>${t(lang,'available')}</h2></div><p>${t(lang,'availableNote')}</p></div><div class="motor-filters" data-reveal><label class="motor-search"><span>⌕</span><input id="search" type="search" placeholder="${t(lang,'search')}" aria-label="${t(lang,'search')}"></label><select id="kind" aria-label="${t(lang,'all')}"><option value="All">${t(lang,'all')}</option>${kinds.map(kind=>`<option value="${esc(kind)}">${esc(kind)}</option>`).join('')}</select><div class="car-intent"><button class="active" data-car-intent="All">${t(lang,'all')}</button><button data-car-intent="Sale">${t(lang,'sale')}</button><button data-car-intent="Rent">${t(lang,'rent')}</button></div><span id="result-count"></span></div><div id="grid" class="motor-grid"></div><p id="empty" hidden>${lang==='te'?'మీ వెతుకులాటకు కార్లు లేవు.':'No cars match this search.'}</p><button id="load-more-cars" class="load-more">${t(lang,'more')} ↓</button></section>
 <section id="approach" class="motor-approach"><div data-reveal><span class="motor-index">03 / ${t(lang,'about')}</span><h2>${t(lang,'steps')}</h2></div><div class="motor-steps"><article data-reveal><span>01</span><h3>${t(lang,'stepOne')}</h3><p>${t(lang,'stepOneText')}</p></article><article data-reveal><span>02</span><h3>${t(lang,'stepTwo')}</h3><p>${t(lang,'stepTwoText')}</p></article><article data-reveal><span>03</span><h3>${t(lang,'stepThree')}</h3><p>${t(lang,'stepThreeText')}</p></article></div></section>
 <section class="motor-sell" data-reveal><span class="motor-index">04 / ${lang==='te'?'అమ్మకం':'SELL'}</span><div><h2>${t(lang,'sell')}</h2><p>${t(lang,'sellText')}</p></div><button data-call>${t(lang,'sellCta')} ↗</button></section></main><footer class="car-footer"><b>RS ${lang==='te'?'మోటార్':'MOTOR'}</b><span>${t(lang,'sample')}</span><a href="/boutique.html">${t(lang,'back')} ↗</a></footer>${dialogs()}`;
}

export function motorCard(item,{lang,pic,esc}){
 const name=title(item,lang),photo=item.photos?.[0]||item.image,mediaCount=(item.photos?.length||0)+(item.videos?.length||0);
 return `<button class="car-card" data-detail="${esc(item.id)}" aria-label="${esc(name)}"><div class="car-card-photo">${pic(photo,name)}<span>${item.intent==='Rent'?t(lang,'rent'):t(lang,'sale')}</span></div><div class="car-card-body"><div class="car-card-line"><span>${esc(category(item,lang))}</span><span>${mediaCount} ${lang==='te'?'మీడియా':'media'}</span></div><h3>${esc(name)}</h3><p>${esc(detail(item,lang))}</p><div class="car-card-foot"><strong>${esc(amount(item,lang))}</strong><span>${t(lang,'view')} ↗</span></div></div></button>`;
}
