// Sample content only. Replace every listing, price and photo before publishing.
export const photos = {
  estateHero: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1800&q=85',
  boutiqueHero: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=1800&q=85',
};

export const estate = [
  {id:'e1', title:'Coastal Courtyard Villa',titleTe:'తీర ప్రాంత ప్రాంగణ విల్లా', kind:'Villa', intent:'Sale', location:'Madhurawada · Visakhapatnam',locationTe:'మధురవాడ · విశాఖపట్నం', price:'₹2.85 Cr', detail:'4 beds · 3,200 sq ft', amenities:'Parking, Water supply, Balcony, Power backup',amenitiesTe:'పార్కింగ్, నీటి సరఫరా, బాల్కనీ, విద్యుత్ బ్యాకప్', image:'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1000&q=85', description:'Illustrative villa listing in Madhurawada. Ask for the actual floor plan, ownership documents, site photos and viewing availability before making a decision.',descriptionTe:'మధురవాడలో నమూనా విల్లా ప్రకటన. నిర్ణయం తీసుకునే ముందు నిజమైన ఫ్లోర్ ప్లాన్, యాజమాన్య పత్రాలు, స్థల ఫోటోలు, సందర్శన వివరాలు అడగండి.'},
  {id:'e2', title:'Seaside Apartment',titleTe:'సముద్రతీర అపార్ట్‌మెంట్', kind:'Flat', intent:'Rent', location:'MVP Colony · Visakhapatnam',locationTe:'ఎంవీపీ కాలనీ · విశాఖపట్నం', price:'₹42,000 / mo', detail:'3 beds · 1,850 sq ft', amenities:'Lift, Parking, Water supply, Security',amenitiesTe:'లిఫ్ట్, పార్కింగ్, నీటి సరఫరా, భద్రత', image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1000&q=85', description:'Illustrative rental in MVP Colony. Confirm the deposit, maintenance, parking, exact address and availability during a call.',descriptionTe:'ఎంవీపీ కాలనీలో నమూనా అద్దె ప్రకటన. డిపాజిట్, నిర్వహణ ఖర్చు, పార్కింగ్, ఖచ్చితమైన చిరునామా, అందుబాటు గురించి కాల్‌లో నిర్ధారించుకోండి.'},
  {id:'e3', title:'Eastern Family Home',titleTe:'తూర్పు కుటుంబ గృహం', kind:'House', intent:'Sale', location:'Gajuwaka · Visakhapatnam',locationTe:'గాజువాక · విశాఖపట్నం', price:'₹1.95 Cr', detail:'3 beds · 2,400 sq ft', amenities:'Parking, Water supply, Open space',amenitiesTe:'పార్కింగ్, నీటి సరఫరా, ఖాళీ స్థలం', image:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=1000&q=85', description:'Illustrative home listing. The exact location, built area and ownership details must be verified before publication.',descriptionTe:'నమూనా ఇంటి ప్రకటన. ఖచ్చితమైన స్థలం, నిర్మాణ విస్తీర్ణం, యాజమాన్య వివరాలను ప్రచురించే ముందు నిర్ధారించాలి.'},
  {id:'e4', title:'Garden View Flat',titleTe:'గార్డెన్ వ్యూ ఫ్లాట్', kind:'Flat', intent:'Rent', location:'Seethammadhara · Visakhapatnam',locationTe:'సీతమ్మధార · విశాఖపట్నం', price:'₹28,000 / mo', detail:'2 beds · 1,350 sq ft', amenities:'Lift, Balcony, Parking',amenitiesTe:'లిఫ్ట్, బాల్కనీ, పార్కింగ్', image:'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1000&q=85', description:'Illustrative two-bedroom rental. Ask for the complete monthly cost, move-in date and a visit before shortlisting.',descriptionTe:'నమూనా రెండు పడకగదుల అద్దె ప్రకటన. ఎంపికకు ముందు మొత్తం నెలవారీ ఖర్చు, ప్రవేశ తేదీ, సందర్శన గురించి అడగండి.'},
  {id:'e5', title:'Araku Road Plot',titleTe:'అరకు రోడ్ ప్లాట్', kind:'Plot', intent:'Sale', location:'Anandapuram · Visakhapatnam',locationTe:'ఆనందపురం · విశాఖపట్నం', price:'₹94 Lakh', detail:'2,100 sq ft', amenities:'Road access, Water supply, Open space',amenitiesTe:'రహదారి, నీటి సరఫరా, ఖాళీ స్థలం', image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1000&q=85', description:'Illustrative plot listing near Anandapuram. Confirm the survey number, access road, permitted use, approvals and documents independently.',descriptionTe:'ఆనందపురం సమీపంలోని నమూనా ప్లాట్ ప్రకటన. సర్వే నంబర్, రహదారి, భూమి వినియోగం, అనుమతులు, పత్రాలను స్వతంత్రంగా నిర్ధారించుకోండి.'},
  {id:'e6', title:'City Work Space',titleTe:'సిటీ వర్క్ స్పేస్', kind:'Commercial', intent:'Rent', location:'Dwaraka Nagar · Visakhapatnam',locationTe:'ద్వారకా నగర్ · విశాఖపట్నం', price:'₹1.2 L / mo', detail:'2,600 sq ft', amenities:'Parking, Lift, Power backup',amenitiesTe:'పార్కింగ్, లిఫ్ట్, విద్యుత్ బ్యాకప్', image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1000&q=85', description:'Illustrative office rental. Confirm permitted use, fit-out, service charges and lease terms before arranging a visit.',descriptionTe:'నమూనా కార్యాలయ అద్దె ప్రకటన. సందర్శనకు ముందు అనుమతించిన వినియోగం, ఫిట్ అవుట్, అదనపు ఖర్చులు, లీజు నిబంధనలు నిర్ధారించుకోండి.'},
  {id:'e7', title:'Harbour Link Commercial Plot',titleTe:'హార్బర్ లింక్ వాణిజ్య ప్లాట్',kind:'Commercial plot',intent:'Sale',location:'Sheela Nagar · Visakhapatnam',locationTe:'షీలా నగర్ · విశాఖపట్నం',price:'Price on request',detail:'3,000 sq ft',amenities:'Road access, Open space',amenitiesTe:'రహదారి, ఖాళీ స్థలం',image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1000&q=85',description:'Illustrative commercial plot. Verify zoning, permitted use, road width, survey details and title before any commitment.',descriptionTe:'నమూనా వాణిజ్య ప్లాట్. నిర్ణయం తీసుకునే ముందు జోనింగ్, అనుమతించిన వినియోగం, రహదారి వెడల్పు, సర్వే వివరాలు, యాజమాన్యాన్ని నిర్ధారించండి.'}
];

export const boutique = [
  {id:'b1', title:'The City Coat', kind:'Outerwear',topSeller:true, price:'₹3,890', sizes:['S','M','L','XL'],material:'Fabric composition to confirm',fit:'Fit measurements to confirm',care:'Care instructions to confirm', image:'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=900&q=85', description:'Burgundy coat with a raised collar. Fabric and fit details will be added with the real item.'},
  {id:'b2', title:'Dusk Draped Dress', kind:'Dresses',topSeller:true, price:'₹5,490', sizes:['XS','S','M','L'],material:'Fabric composition to confirm',fit:'Size chart to confirm',care:'Care instructions to confirm', image:'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=900&q=85', description:'Pale blue draped dress with a wrap front and side tie. Sample product image.'},
  {id:'b3', title:'Terracotta Bomber', kind:'Outerwear', price:'₹2,690', sizes:['S','M','L','XL','XXL'], image:'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=900&q=85', description:'Terracotta zip-front bomber with ribbed neckline and cuffs. Sample product image.'},
  {id:'b4', title:'Denim Day Dress', kind:'Dresses',topSeller:true, price:'₹6,990', sizes:['S','M','L'], image:'https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=900&q=85', description:'Short-sleeved denim dress with a button front. Sample product image.'},
  {id:'b5', title:'Weekend Tee', kind:'T-shirts', price:'₹2,490', sizes:['S','M','L','XL'], image:'https://images.unsplash.com/photo-1564859228273-274232fdb516?w=900&q=85', description:'White graphic crew-neck tee. Sample product image.'},
  {id:'b6', title:'Checked City Coat', kind:'Outerwear', price:'₹4,290', sizes:['XS','S','M','L'], image:'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=900&q=85', description:'Dark checked outer layer with a relaxed cut. Sample product image.'}
];

export const cars = [
  {id:'c1', title:'City Cruiser',titleTe:'సిటీ క్రూజర్', kind:'Pre-owned',intent:'Sale', price:'Price on request', detail:'2022 · Petrol · 22,000 km',detailTe:'2022 · పెట్రోల్ · 22,000 కి.మీ.', image:'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1000&q=85', description:'A carefully presented sample vehicle listing.',descriptionTe:'ఇది నమూనా కారు ప్రకటన. నిజమైన వివరాలు తరువాత జోడించబడతాయి.'},
  {id:'c2', title:'Grand Touring',titleTe:'గ్రాండ్ టూరింగ్', kind:'Pre-owned',intent:'Sale', price:'Price on request', detail:'2021 · Diesel · 31,000 km',detailTe:'2021 · డీజిల్ · 31,000 కి.మీ.', image:'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1000&q=85', description:'A sample listing showing the format for car enquiries.',descriptionTe:'కారు విచారణ ఎలా ఉంటుందో చూపించే నమూనా ప్రకటన.'},
  {id:'c3', title:'Weekend Rental',titleTe:'వారాంతపు అద్దె కారు', kind:'Rental',intent:'Rent', price:'Price on request', detail:'2023 · Petrol · Self-drive',detailTe:'2023 · పెట్రోల్ · స్వయంగా నడపండి', image:'https://images.unsplash.com/photo-1507136566006-cfc505b114fc?w=1000&q=85', description:'Sample rental listing. Availability and terms require confirmation.',descriptionTe:'ఇది నమూనా అద్దె కారు ప్రకటన. అందుబాటు, నిబంధనలు నిర్ధారించాలి.'}
];
